replicaCount: 1

image:
  repository: blackicebird/2048
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: "game2048-app"
fullnameOverride: "game2048-chart"

serviceAccount:
  create: true
  annotations: {}
  name: "game2048-service-account"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  # ClusterIP
  type: NodePort
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
